version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ide_db
    ports:
      - "3306:3306"
    volumes:
      - ide_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  ide_data: